# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin:$HOME/tools/scripts:$HOME/disk2/sdk/montavista/pro/devkit/ppc/82xx/bin

export PATH
